nygardk/react-share

build/share-buttons.js
build/social-media-share-links.js
package.json
src/share-buttons.jsx
src/social-media-share-links.jsx

Passed along `via` and `hashtags` attributes to twitter sharing; added `description` attribute to pinterest sharing.

add sharing attributes to twitter and pinterest

---

src/generateIcon.jsx

@nygardk It might be best to be have only the necessary styles (width/height) and leave the rest to the user, what do you think?
Example: I'm using the components within a flexbox and the `display: 'inline-block'` is causing problems. If someone wants to use display: inline-block, then they should add it as a class?

Remove unnecessary style

---

src/share-count-getters.jsx

Make getFacebookShareCount call the callback with undefined if any network error occurs like other share count getters do.
Nice lib btw :)

Call callback on error

---

README.md

Title is not required for the Facebook share. Removes Facebook from that list

---

demos/demo0/Demo.jsx
src/share-buttons.jsx
src/utils.js

* Make windows width settable to fix pinterest window's width is wide enough.
* Previously, pinterest window is like following which will make user think they may not be able to login. So we should make windows size can be adjustable, so when people use this library, they can decide how big the window it is.

make windows width settable

---

package.json
src/generateIcon.jsx
src/share-counts.jsx

Actually removing deprecated behavior for a smoother transition to React v16.

Remove React createClass and PropTypes warnings

---

package.json

This adopts the common practice of using more permissive versioning. This change helps consumers reduce their bundle size by avoiding multiple copies of the same library.

Prefix dependency versions with caret (^)

---

src/share-buttons.jsx

This should address Issue #80. This allows keyboards (and as a result, assistive technology) to access these controls. While a button element would have been preferable, this method doesn't impact styling and achieves the same result.

Made share buttons accessible to keyboards and assistive tech

---

src/social-media-share-links.jsx

This is documented in their FAQ: https://faq.whatsapp.com/en/26000030/?category=5245251
It opens the desktop/iOS/android app if installed, otherwise it directs the user to the web application.

Update What's App share URL to use their new API

---

demos/demo0/Demo.jsx
src/share-buttons.jsx
src/social-media-share-links.jsx

https://developers.facebook.com/docs/apps/changelog
_v2.9
Introduced April 18th, 2017_
> 90-Day Deprecations
> The following fields are deprecated for edges and dialogs that allow attaching links to posts:
- picture
- name
- caption
- thumbnail
- description
From now on, only quotes working in facebook share dialog.

Update deprecated fields in facebook share dialog

---

src/social-media-share-links.jsx

This pull request fixes the bug in `title`-prop of the WhatsApp shares.
`title`-prop is optional. But omitting it will currently corrupt the message with `undefined ` -prefix. This commit fixes the issue.

Fixed title-prop optionality for WhatsApp shares

---

package.json
src/share-count-getters.jsx
src/utils.js

I was checking my bundle sizes when I discovered the following: `react-share` had a dependency to `platform`. This leads to large bundles when `react-share` is used.
The dependency to `platform` brings in about 40kB of JavaScript (perhaps ~11-12kB when gzipped?). It thus effectively doubles the size of `react-share` and brings an unnecessary burden to slow mobile devices & networks.
`platform` was only used to check for IE < 11 and IE < 10. I replaced these checks with a regex. Check https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx for reference.
I've tested the new detection with these browsers: IE9, IE 10, IE 11 and Chrome. I tried to keep code changes to a minimum.
***
On another topic: would it be ok if I take a look at setting up ES6 module builds for the project as …

Reduce bundle sizes by removing dependency to 'platform'. 

---

src/EmailShareButton.js

`url` is used as email body unless `body` prop has been specified. This conforms to the README.md documentation. See issue #132 
However the `url` is not used if `body` has been defined. I think this is a safe change and should not break existing usage.

EmailShareButton: url is used as the default email body. Fixes #132.

---

src/utils/createShareButton.jsx

The `beforeOnClick` callback is now invoked for all share buttons.
This has been tested this with `beforeOnClick` with and without Promises. Everything seemed to be working and this should be safe to merge.
@nygardk would it be ok if I merge this + #136 + #138 and update the changelog accordingly?

beforeOnClick is invoked for EmailShareButtons. Fixes #133.

---

CHANGELOG.md
package.json

Adds support for webpack 4 tree shaking with `sideEffects: false` declared in `package.json`.
References:
- #147 
- https://github.com/webpack/webpack/tree/master/examples/side-effects
- https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false

Added support for webpack 4 tree shaking with `sideEffects: false` 

---

src/utils/createShareButton.jsx

Space should also work as 'click' for role button.
https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

Add space to fix accessibility error.

---

README.md

Small fix: 
When I run this: `npm run run-demo` it says `missing script: run-demo` , because it should be `npm run run-demos`

Error: missing script: run-demo

---

src/WhatsappShareButton.js

Checking if mobile, url would be 'api'. Instead in desktop browser would open 'web' whatsapp to share

Whatsapp button should check if mobile

---

README.md
demo/Demo.jsx
src/ViberShareButton.js

This PR fixes the following:
- No extra spaces prepended to the url when a title has not been defined
- Demo source code does not try to set up an non-existing `body`-prop
- Exposed the separator as a prop

Viber shares no longer prepend space and expose the separator as a prop.

---

src/WeiboShareButton.js

Removes assertion for image parameter on weiboLink. (Should not be required, right?)

Fix: remove assert for image on weiboLink

---

src/WeiboShareButton.js

fix weibo share does not contain url

---

demo/Demo.jsx
src/OKShareButton.js
src/WeiboShareButton.js
src/utils/createShareButton.jsx

- Adds `windowPosition` prop for share buttons
- Refactors share window position calculation logic
- Sets `windowPosition="screenCenter"` as default for `WeiboShareButton` to prevent the window from jumping after opening
(as discussed at https://github.com/nygardk/react-share/pull/210#pullrequestreview-199927644)

Feat: share button windowPosition prop

---

src/utils/createShareButton.jsx

This branch uses `React.forwardRef` to add `ref` support to the share buttons. I implemented this changed based on the instructions listed [here](https://reactjs.org/docs/forwarding-refs.html).
I was originally inspired to make this change as a result of a new caveat in `@material-ui/core` v4 (https://material-ui.com/guides/composition/#caveat-with-refs) where components passed to the `component` prop of certain MUI components, like a `Button` must support refs. The MUI `component` prop is useful if I wanted to make a share button that follows the style of the other buttons in my app. 
For example:
```js
import {TwitterShareButton} from 'react-share';
import {Button} from '@material-ui/core';
// doesn't work anymore since TwitterShareButton doesn't support refs :(
<Button …
```

Support refs

---

src/utils/shareCountFactory.jsx

To get rid of the warnings in the console.
See 
* https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes
* https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods

Replace unsafe lifecycle method `componentWillReceiveProps`

---

src/hocs/createShareCount.tsx

Fixes #279
Removes the `getCount` prop from the `rest` properties, which are forwarded to the native DOM element.

Remove `getCount` prop from DOM node

---

src/TwitterShareButton.ts

If you pass Twitter an empty string (which is what happens when you call Array.join on an empty array), Twitter adds an empty hashtag to the post when sharing with the native app on iOS. I haven't checked Android. Web seems fine. See issue #284.

Handle no hashtag for Twitter

---

src/OKShareCount.ts

Hi! This PR resolves issue with multiple Odnoklassniki(ok.ru) share count components on same page.
Issue: It send static uid to OK API and doesn't read uid from response, so after response it calls always last callback in array `window.OK.callbacks` and share count updated only on last element on page

Call correct callback with multiple Odnoklassniki share button

---

src/ViberShareButton.ts

In the current implementation, if the separator is not provided on the component it translates to `undefined`
viber://forward?text=Testundefinedwww.google.com

Add default viber separator

---

src/VKShareCount.ts

Global object **window.VK** can be used by official api https://vk.com/js/api/openapi.js what can cause conflicts and errors like:
> Uncaught TypeError: Cannot read property 'length' of undefined
>     at Object.getCount (VKShareCount.js:14)

Secure record in window.VK

---

src/TelegramShareButton.ts

Telegram is using `https://t.me/share/url?url={url}&text={text}` format for [custom share button](https://core.telegram.org/widgets/share#custom-buttons) now. 
So without `/url` we have problems with redirect on IOS.

Update telegram link

---

.changeset/dirty-ladybugs-study.md
src/RedditShareButton.ts

fix(Reddit share): Automatically populate link in Reddit share URL
Issue: [#546](https://github.com/nygardk/react-share/issues/546)
Problem:
- The link was not automatically populated when sharing via Reddit.
Solution:
- Added `/web` as a route prefix before `/submit` in the Reddit share URL to ensure the link populates correctly.
Testing:
- Verified that the link is now correctly populated in Reddit share previews.

Reddit Share button Update the submit URL

---

.changeset/late-horses-enjoy.md
src/ShareButton.tsx

fix: prevent title from being passed to the button element
